# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-14 00:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acolhido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('data_nasc', models.DateField(default=datetime.date.today)),
                ('data_entrada', models.DateField(default=datetime.date.today)),
                ('local_nasc', models.CharField(max_length=50)),
                ('uf', models.CharField(default='SP', max_length=2)),
                ('imagem', models.ImageField(default='media/default.png', upload_to='img_acolhidos')),
                ('nome_mae', models.CharField(default='', max_length=40)),
                ('resp_mae', models.BooleanField(default=False)),
                ('nome_pai', models.CharField(default='', max_length=40)),
                ('resp_pai', models.BooleanField(default=False)),
                ('nome_resp', models.CharField(default='', max_length=40)),
                ('resp_resp', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlr_disponivel', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('data_entrada', models.DateField(default=datetime.date.today)),
                ('imagem', models.ImageField(default='media/default.png', upload_to='img_doadores')),
                ('tipo', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=15)),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(default='SP', max_length=2)),
                ('tel_residencial', models.CharField(max_length=10)),
                ('tel_celular', models.CharField(max_length=10)),
                ('tel_comercial', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('DOACAO', 'Doação')], max_length=7)),
                ('descricao', models.CharField(max_length=150)),
                ('data', models.DateField(default=datetime.date.today)),
                ('qtd', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('qtd', models.IntegerField()),
                ('unidade', models.CharField(max_length=20)),
                ('data_validade', models.DateField(default=datetime.date.today)),
                ('preco_entrada', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
