# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-04-19 16:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novo_nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('tipo_doacao', models.CharField(max_length=10)),
                ('qtd', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Juridico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.CharField(max_length=25)),
                ('comarca', models.CharField(max_length=30)),
                ('nro_vara', models.CharField(max_length=2)),
                ('vara', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=65)),
                ('numero', models.CharField(max_length=4)),
                ('complemento', models.CharField(max_length=15)),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=20)),
                ('salario', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=65)),
                ('numero', models.CharField(max_length=4)),
                ('complemento', models.CharField(max_length=15)),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='acolhido',
            name='local_nasc',
        ),
        migrations.RemoveField(
            model_name='doador',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='doador',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='doador',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='doador',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='doador',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='doador',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='doador',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='doador',
            name='uf',
        ),
        migrations.AddField(
            model_name='acolhido',
            name='alergias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='acolhido',
            name='calca',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='acolhido',
            name='calcado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='acolhido',
            name='camiseta',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='acolhido',
            name='cid_natal',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='acolhido',
            name='cpf',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='acolhido',
            name='intima',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='acolhido',
            name='qtd_aborto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acolhido',
            name='renda',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='acolhido',
            name='rg',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='acolhido',
            name='sangue',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='acolhido',
            name='sexo',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='acolhido',
            name='ssp',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='doador',
            name='alimenticio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doador',
            name='financeiro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doador',
            name='vestuario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doador',
            name='voluntario',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='acolhido',
            name='data_entrada',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='acolhido',
            name='data_nasc',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='acolhido',
            name='imagem',
            field=models.ImageField(blank=True, default='media/default.png', upload_to='img_acolhidos'),
        ),
        migrations.AlterField(
            model_name='acolhido',
            name='nome',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='acolhido',
            name='nome_mae',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='acolhido',
            name='nome_pai',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='acolhido',
            name='nome_resp',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='acolhido',
            name='uf',
            field=models.CharField(blank=True, default='SP', max_length=2),
        ),
    ]
