# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-04-27 21:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20190419_1301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trabalho',
        ),
        migrations.RemoveField(
            model_name='acolhido',
            name='resp_resp',
        ),
        migrations.RemoveField(
            model_name='doador',
            name='tel_celular',
        ),
        migrations.RemoveField(
            model_name='doador',
            name='tel_comercial',
        ),
        migrations.RemoveField(
            model_name='doador',
            name='tel_residencial',
        ),
        migrations.AddField(
            model_name='acolhido',
            name='grau_resp',
            field=models.CharField(blank=True, choices=[('MÃE', 'Mãe'), ('PAI', 'Pai'), ('AVÓ', 'Avó'), ('AVÔ', 'Avô'), ('OUT', 'Outro'), ('NEN', 'Nenhum')], max_length=3),
        ),
        migrations.AddField(
            model_name='doador',
            name='tel_1',
            field=models.CharField(default='0', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doador',
            name='tel_2',
            field=models.CharField(default='0', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juridico',
            name='acolhido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.Acolhido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residencia',
            name='acolhido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.Acolhido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acolhido',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='acolhido',
            name='data_entrada',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='acolhido',
            name='data_nasc',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='acolhido',
            name='sangue',
            field=models.CharField(blank=True, choices=[('', 'Desconhecido'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='acolhido',
            name='ssp',
            field=localflavor.br.models.BRStateField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='acolhido',
            name='uf',
            field=localflavor.br.models.BRStateField(blank=True, default='SP', max_length=2),
        ),
        migrations.AlterField(
            model_name='juridico',
            name='comarca',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='juridico',
            name='nro_vara',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='juridico',
            name='processo',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='juridico',
            name='vara',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='bairro',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='cidade',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='complemento',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='logradouro',
            field=models.CharField(blank=True, max_length=65),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='numero',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
