# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-05-05 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20190427_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='acolhido',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
