# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-05-18 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_acolhido_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='data_validade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_entrada',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='unidade',
        ),
        migrations.AlterField(
            model_name='acolhido',
            name='sangue',
            field=models.CharField(blank=True, choices=[('', 'Selecione'), ('NI', 'Não informado'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='doador',
            name='email',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='doador',
            name='tel_1',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='doador',
            name='tel_2',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
