# Generated by Django 2.2.1 on 2019-08-31 19:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_auto_20190518_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='qtd',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='tipo_doacao',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='valor',
        ),
        migrations.AddField(
            model_name='doacao',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='doacao',
            name='doador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.Doador'),
        ),
        migrations.AlterField(
            model_name='acolhido',
            name='resp_mae',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='acolhido',
            name='resp_pai',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='ItemDoacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=30)),
                ('qtd', models.IntegerField()),
                ('id_doacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='sistema.Doacao')),
            ],
        ),
        migrations.CreateModel(
            name='DinheiroDoacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('id_doacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinheiro', to='sistema.Doacao')),
            ],
        ),
    ]
