# Generated by Django 2.2.1 on 2019-09-10 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_auto_20190904_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='data_registro',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='dinheirodoacao',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
    ]
